### ISSUE TITLE
No module named pandas

### ISSUE THREAD

**Issue by mikelauff** [DaveL17/BikeShare#1]
Hi. I'm hoping to use your plugin, but here's what the Indigo log reveals after loading the plugin:
```
Nov 10, 2020 at 10:58:42 AM
   Installing and enabling plugin Bike Share v2.0.06
   Loading plugin "Bike Share 2.0.06"
   Starting plugin "Bike Share 2.0.06" (pid 65402)
   Bike Share Error                Error in plugin execution InitializeMain:

Traceback (most recent call last):
  File "plugin.py", line 31, in <module>
ImportError: No module named pandas

   Stopping plugin "Bike Share 2.0.06" (pid 65402)
   Stopped plugin "Bike Share 2.0.06"

```
I'm using Indigo 7.4.1 on macOS Catalina 10.15.7

**Comment by DaveL17** [comment]
Hello Mike - I’m sorry that you’re having trouble with the plugin.  The Pandas Python module ships with OS X (at least up to and including Catalina); so I’m not sure why Indigo is unable to find it.  What version of OS X are you using?

Please, try a couple of tests.

1.  From the Indigo Plugins menu, select “Open Scripting Shell”.  Do you get the error there?  (I expect you will).  You can enter “exit()” to exit the shell (no quotes, include the parens).

2. Open an OS X terminal window and try the same thing.  Do you also get the error there?

3. Have you installed any additional Python instances on your Indigo machine?  Sometimes, that can mess with the machine's path.

Please let me know.
Dave

**Comment by mikelauff** [comment]
Thanks for the quick reply. I'm using Indigo 7.4.1 on macOS Catalina 10.15.7.

I'm not sure of the tests you want me to perform in 1. and 2. Just open the Shell & Terminal? Both work fine. Is there a command you want me to execute?

Here's the result of 1.
```
Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
Connected to Indigo Server v7.4.1, api v2.3 (localhost:1176)
>>> 

```
Here's the result of 2. I've added the output of which python and python --version FYI
```
Last login: Tue Nov 10 16:22:57 on ttys000
mike@Condo-Mac-mini ~ % which python
/usr/bin/python
mike@Condo-Mac-mini ~ % python --version
Python 2.7.16
mike@Condo-Mac-mini ~ % 

```

This is a new Mac mini with a fresh install of the OS and Indigo. No additional Python instances have been added.

**Comment by DaveL17** [comment]
Wow - somehow a chuck is missing.

1. In the Indigo Plugin Shell, type the command:
Import pandas

2. In the OS X Shell, type the following commands:
python2.7
Import pandas

Both *should* run without errors, but expect that will not be the case in this instance.

**Comment by mikelauff** [comment]
Results of 1.
```
Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
Connected to Indigo Server v7.4.1, api v2.3 (localhost:1176)
>>> Import pandas
  File "<console>", line 1
    Import pandas
                ^
SyntaxError: invalid syntax
>>> 

```
Results of 2.
```
Last login: Tue Nov 10 16:33:37 on ttys000
mike@Condo-Mac-mini ~ % python2.7

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> Import pandas
  File "<stdin>", line 1
    Import pandas
                ^
SyntaxError: invalid syntax
>>> 

```

**Comment by DaveL17** [comment]
Apologies.  The term ‘import' should not be capitalized.  That’s Tim Cook thinking he knows what I want better than I do.  :o)

**Comment by mikelauff** [comment]
using **import**
```
Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
Connected to Indigo Server v7.4.1, api v2.3 (localhost:1176)
>>> import pandas
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named pandas
>>> 
```
Results of 2.
```
Last login: Tue Nov 10 16:44:51 on ttys000
mike@Condo-Mac-mini ~ % python2.7

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pandas
>>> 

```

**Comment by DaveL17** [comment]
Yep — that’s what I expected would happen, but it also confirms that it’s not just an issue with Indigo.  The pandas module is obviously required in order to use the plugin.  It’s possible for you to install it yourself, but — depending on whether you’re comfortable making changes to your machine with the shell — it’s not necessarily a straightforward deal.  I can give you some pointers, but can’t guarantee your success or ensure that it will be trouble-free.

**Comment by mikelauff** [comment]
I really appreciate your help. I'm comfortable making changes and understand you can't guarantee my results. Thanks!

**Comment by DaveL17** [comment]
To install pip (if needed):

     https://pip.pypa.io/en/stable/installing/

You’ll need to ensure that you’re installing it onto Python 2.7 as Catalina also has Python 3 which the shell will default to.  Once pip is installed, 

     pip install pandas

**Comment by mikelauff** [comment]
Thanks again. That got me past all previous hurdles, and I'm now able to run the plugin, configure it with System: Indego (Philadelphia, PA), and add a couple of stations. It seems that the data returned doesn't contain "capacity" info?

```
Nov 10, 2020 at 5:58:48 PM
   Reloading plugin "Bike Share 2.0.06"
   Stopping plugin "Bike Share 2.0.06" (pid 66971)
   Stopped plugin "Bike Share 2.0.06"
   Starting plugin "Bike Share 2.0.06" (pid 66990)
   Bike Share                      
   Bike Share                      =================================================== Initializing New Plugin Session ===================================================
   Bike Share                      Plugin name:                    Bike Share
   Bike Share                      Plugin version:                 2.0.06
   Bike Share                      Plugin ID:                      com.fogbert.indigoplugin.bikeShare
   Bike Share                      Indigo version:                 7.4.1
   Bike Share                      Python version:                 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
   Bike Share                      Mac OS Version:                 10.15.7
   Bike Share                      Process ID:                     66990
   Bike Share                      =======================================================================================================================================
   Started plugin "Bike Share 2.0.06"
   Bike Share Error                exception in deviceStartComm(12th & Chestnut Bike Station): 'capacity'
   Bike Share Error                exception in deviceStartComm(17th & Locust Bike Station): 'capacity'
   Bike Share Critical Error       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TRACEBACK !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   Bike Share Critical Error       !!! Traceback (most recent call last):
   Bike Share Critical Error       !!!   File "plugin.py", line 596, in refresh_bike_data
   Bike Share Critical Error       !!!     self.parse_bike_data(dev)
   Bike Share Critical Error       !!!   File "plugin.py", line 466, in parse_bike_data
   Bike Share Critical Error       !!!     states_list.append({'key': key, 'value': station[key]})
   Bike Share Critical Error       !!! KeyError: 'capacity'
   Bike Share Critical Error       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   Bike Share Critical Error       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TRACEBACK !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   Bike Share Critical Error       !!! Traceback (most recent call last):
   Bike Share Critical Error       !!!   File "plugin.py", line 596, in refresh_bike_data
   Bike Share Critical Error       !!!     self.parse_bike_data(dev)
   Bike Share Critical Error       !!!   File "plugin.py", line 466, in parse_bike_data
   Bike Share Critical Error       !!!     states_list.append({'key': key, 'value': station[key]})
   Bike Share Critical Error       !!! KeyError: 'capacity'
   Bike Share Critical Error       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by DaveL17** [comment]
We’re making good headway.  What service are you attempting to use?

**Comment by mikelauff** [comment]
Indego (Philadelphia, PA)

**Comment by DaveL17** [comment]
OK — I can reproduce the error with that service.

My understanding of the API is that the service should support dock capacity, but no matter.  (Interestingly, I didn’t get the error with another Indego location.)

I’ll fix the plugin to address this.  Please hang tight and I’ll upload a new version soon.

**Comment by DaveL17** [comment]
Hi Mike - I've uploaded a new build of the plugin that should be more resilient to situations where expected data elements aren't present in the API data retrieved from the bike sharing service.  Please try the new version at your convenience.  You'll need to download it from GitHub as I haven't yet released this version in the Indigo Plugin store.

You can get it from the main repo page or directly [here](https://github.com/DaveL17/BikeShare/archive/master.zip)

**Comment by mikelauff** [comment]
You're the best! This latest version (2.0.07) is working for me. There are a few elements that remain "Unknown" but I've got enough to make it useful, including num_bikes_available and num_docks_available. Many, many thanks!

![image](https://user-images.githubusercontent.com/138063/98833300-db743b80-240b-11eb-8341-1a0ac560739e.png)

**Comment by DaveL17** [comment]
That's good to hear.  The "Unknown" value is the safety net when an API field is not provided by the data service.  The standard that the services use (GBFS) contains fields that clearly aren't always used.  The plugin doesn't attempt to use all of them, but even the limited list is apparently incomplete for some. Let me know if you see any ways that the plugin could be more useful.
